### PR TITLE
Update ember-youtube.js

### PR DESCRIPTION
**Pull request by lordkada**
The fullscreen could be an external parameter (ref #30)

### CODE REVIEW

**Comment by oskarrough** [comment]
Thank you.

**Comment by lordkada** [comment]
@oskarrough just a question: do you have any plan to release a new version? I can see that since the last available (0.5.3) there's just one commit (my patch), but for my own stuffs I'd need to access from npm instead of github. Thanks for your work! ;-)

**Comment by oskarrough** [comment]
Thank you for reminding me. I just released 0.6.0 on NPM where I've removed the default YouTube options and also the `fs` property you added. Now you'll define it through `playerVars` object like the rest of the parameters.

Hope it's good like this!

**Comment by lordkada** [comment]
It looks fine to me... many thanks!

**Pull request merged**
